# Generated by Django 4.2.6 on 2023-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bookTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tname", models.CharField(max_length=100)),
                ("Temail", models.CharField(max_length=100)),
                ("Tphone", models.CharField(max_length=100)),
                ("Tdate", models.CharField(max_length=100)),
                ("Ttime", models.CharField(max_length=100)),
                ("Tmessage", models.CharField(max_length=100)),
            ],
        ),
    ]
