# Generated by Django 4.2.6 on 2023-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restro_PUB", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktable",
            name="Tpeople",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Tdate",
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Temail",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Tmessage",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Tphone",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Ttime",
            field=models.TimeField(max_length=100),
        ),
    ]
