# Generated by Django 4.2.6 on 2023-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restro_PUB", "0002_booktable_tpeople_alter_booktable_tdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ContactName", models.CharField(max_length=100)),
                ("ContactEmail", models.EmailField(max_length=254)),
                ("subject", models.TextField(max_length=100)),
                ("ContactMessage", models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Tdate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booktable",
            name="Ttime",
            field=models.TimeField(),
        ),
    ]
